src/adminlte/routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::get('', 'DashboardController@index')->name('admin');

/****************************** ADMINISTRATOR ************************/
Route::resource('administrators', 'AdministratorController');

src/adminlte/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', 'Admin\AuthController@login')->name('admin.login');
Route::post('admin/login', 'Admin\AuthController@postLogin')->name('admin.post.login');
Route::get('admin/logout', 'Admin\AuthController@logout')->name('admin.logout');

Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth:admin'])
    ->group(base_path('routes/admin.php'));
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

src/adminlte/resources/views/layouts/admin_partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
    <b>AdminLTE Portal</b>
    </div>
    <strong>© 2019 <a href="https://ryugaku.merise.asia/">AdminLTE Co.Ltd</a>.</strong> All rights
    reserved.
</footer>

src/adminlte/resources/views/layouts/admin_partials/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>D</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>AD</b>MIN</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="{{ route('admin.logout') }}">
                        <i class="fa fa-share"></i>
                        <span class="hidden-xs">Log out</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>

src/adminlte/resources/views/layouts/admin_partials/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="li-link">
                <a class="link" href="{{ route('admin') }}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span>{{__('admin.sidebar.administrator')}}</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="li-link"><a class="link" href="{{ route('administrators.index') }}"><i class="fa fa-circle-o text-aqua"></i>Users</a></li>
                    <li class="li-link"><a class="link" href=""><i class="fa fa-circle-o text-aqua"></i>Roles</a></li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>