src/adminlte/routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::get('', 'DashboardController@index')->name('admin');

/****************************** ADMINISTRATOR ************************/
Route::resource('administrators', 'AdministratorController');

src/adminlte/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', 'Admin\AuthController@login')->name('admin.login');
Route::post('admin/login', 'Admin\AuthController@postLogin')->name('admin.post.login');
Route::get('admin/logout', 'Admin\AuthController@logout')->name('admin.logout');

Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth:admin'])
    ->group(base_path('routes/admin.php'));
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

src/adminlte/app/Http/Controllers/Admin/AdministratorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Administrator\StoreRequest;
use App\Http\Requests\Admin\Administrator\UpdateRequest;
use App\Models\Admin;

class AdministratorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $administrators = Admin::role('Administrator');
        if ($request->name) {
            $administrators = $administrators->where('name', 'like', '%'.$request->name.'%');
        }
        if ($request->email) {
            $administrators = $administrators->where('email', 'like', '%'.$request->email.'%');
        }
        $administrators = $administrators->paginate(config('adminlte.admin.per_page'));
        return view('admin.administrator.index', compact('administrators'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.administrator.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        \DB::beginTransaction();
        try {
            $filename = null;
            if($request->hasFile('avatar')) {
                $file       = $request->file('avatar'); 
                $extension  = $file->getClientOriginalExtension();
                $filename   = uniqid().'_'.time().'_'.date('Ymd').'.'.$extension;
                $uploadDir = 'administrator/';
                $file->storeAs($uploadDir, $filename, config('filesystems.public_disk'));
            }
            $data = [
                'name'          => $request->name,
                'last_name'     => $request->last_name,
                'first_name'    => $request->first_name,
                'last_name_e'   => $request->last_name_e,
                'first_name_e'  => $request->first_name_e,
                'email'         => $request->email,
                'password'      => bcrypt($request->password),
                'gender'        => $request->gender,
                'birthday'      => \Carbon\Carbon::parse($request->birthday)->format('Y-m-d'),
                'avatar'        => $filename,
                'address'       => $request->address,
            ];
            $admin =  Admin::create($data);
            $admin->assignRole('Administrator');

            \DB::commit();
            flash('Created Successfully!')->success()->important();
            return redirect()->route('administrators.index');
        } catch (\Exception $e) {
            \DB::rollBack();
            \Log::error($e->getMessage());
            flash('Create Error')->error()->important();
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $admin = Admin::role('Administrator')->find($id);
        if ($admin !== null) {
            return view('admin.administrator.detail', compact('admin'));
        } else {
            flash('The Administrator could not be found!')->warning()->important();
            return redirect()->route('administrators.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $admin = Admin::role('Administrator')->find($id);
        if ($admin !== null) {
            return view('admin.administrator.edit', compact('admin'));
        } else {
            flash('The Administrator could not be found!')->warning()->important();
            return redirect()->route('administrators.index');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        \DB::beginTransaction();
        try {
            $data_admin = [
                'name'          => $request->name,
                'last_name'     => $request->last_name,
                'first_name'    => $request->first_name,
                'last_name_e'   => $request->last_name_e,
                'first_name_e'  => $request->first_name_e,
                'email'         => $request->email,
                'gender'        => $request->gender,
                'birthday'      => \Carbon\Carbon::parse($request->birthday)->format('Y-m-d'),
                'address'       => $request->address,
            ];
            if ($request->password !== null) {
                $data_admin['password'] = bcrypt($request->password);
            }
            if($request->hasFile('avatar')) {
                $file       = $request->file('avatar'); 
                $extension  = $file->getClientOriginalExtension();
                $filename   = uniqid().'_'.time().'_'.date('Ymd').'.'.$extension;
                $uploadDir = 'administrator/';
                $file->storeAs($uploadDir, $filename, config('filesystems.public_disk'));
                $data_admin['avatar'] = $filename;
                //delete image
                $avatar = Admin::find($id)->avatar;
                \Storage::disk(config('filesystems.public_disk'))->delete($uploadDir.$avatar);
            }
            Admin::role('Administrator')->where('id', $id)->update($data_admin);
            
            \DB::commit();
            flash('Update Successfully!')->success()->important();
            return redirect()->route('administrators.index');
        } catch (\Exception $e) {
            \DB::rollBack();
            \Log::error($e->getMessage());
            flash('Update Error')->error()->important();
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \DB::beginTransaction();
        try {
            $admin = Admin::role('Administrator')->find($id);
            $admin->delete();
            $admin->removeRole('Administrator');
            \DB::commit();
            return back();
        } catch (\Exception $e) {
            \DB::rollBack();
            \Log::notice($e->getMessage());
            return back();
        }
    }
}

src/adminlte/resources/views/admin/administrator/create.blade.php
@extends('layouts.admin')
@section('title', 'Administrator Create')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1 class="breadcrumb-title">
            Administrator
            <small>New</small>
        </h1>
        <div class="pull-right">
            <a href="{{ route('administrators.index') }}" class="btn bg-green btn-flat"><i class="fa fa-list"></i> List</a>
        </div>
    </section>
    <section class="content">
        @include('flash::message')
        <div class="row box-search">
            <div class="col-md-12">
                <div class="box">
                    <!-- /.box-header -->
                    <!-- form start -->
                    @includeIf('admin.administrator.form')
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

src/adminlte/resources/views/admin/administrator/detail.blade.php
@extends('layouts.admin')
@section('title', 'Administrator Detail')
@push('styles')
    <style>
        .btn-edit {
            margin-bottom: 10px;
        }
    </style>
@endpush
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1 class="breadcrumb-title">
            Administrator
            <small>Detail #{{ $admin->id }}</small>
        </h1>
        <div class="pull-right">
            <a href="{{ route('administrators.create') }}" class="btn bg-green btn-flat"><i class="fa fa-plus"></i> New</a>
            <a href="{{ route('administrators.index') }}" class="btn bg-green btn-flat"><i class="fa fa-list"></i> List</a>
        </div>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#infomation" data-toggle="tab" aria-expanded="true">Infomation</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="infomation">
                            <div class="row">
                                <div class="col-md-8">
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <th class="text-center">Administrator Name</th>
                                                <td class="text-center">{{ $admin->name }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Email</th>
                                                <td class="text-center">{{ $admin->email }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Gender</th>
                                                <td class="text-center">{{ $admin->gender ? 'Female' : 'Male' }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Address</th>
                                                <td class="text-center">{{ $admin->address }}</td>
                                            </tr>
                                        </tbody>
                                </table>
                                </div>
                                <div class="col-md-4">
                                    <div class="detail-right text-center">
                                        <div class="w100">
                                            <a href="{{ route('administrators.edit', $admin->id) }}" class="btn btn-primary btn-flat btn-edit"><i class="fa fa-fw fa-edit"></i>Edit</a>
                                        </div>
                                        <div class="w100">
                                            @if($admin->avatar)
                                            <img src="{{ Storage::url('administrator/'.$admin->avatar) }}" alt="" class="img-thumbnail">
                                            @else
                                            <img src="{{ asset('assets/avatars/avatar0.jpg') }}" alt="" class="img-thumbnail">
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

src/adminlte/resources/views/admin/administrator/edit.blade.php
@extends('layouts.admin')
@section('title', 'Administrator Edit')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1 class="breadcrumb-title">
            Administrator
            <small>Edit #{{ $admin->id }}</small>
        </h1>
        <div class="pull-right">
            <a href="{{ route('administrators.create') }}" class="btn bg-green btn-flat"><i class="fa fa-plus"></i> New</a>
            <a href="{{ route('administrators.index') }}" class="btn bg-green btn-flat"><i class="fa fa-list"></i> List</a>
        </div>
    </section>
    <section class="content">
        @include('flash::message')
        <div class="row box-search">
            <div class="col-md-12">
                <div class="box">
                    <!-- /.box-header -->
                    <!-- form start -->
                    @includeIf('admin.administrator.form')
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

src/adminlte/resources/views/admin/administrator/form.blade.php
@php
    $isEdit = isset($admin->id) && $admin->id > 0 ? 1 : 0
@endphp
{!! Form::open(['method' => 'POST', 'url' => $isEdit ? route("administrators.update", $admin->id) : route("administrators.store"), 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}
    @if($isEdit)
    @method('PUT')
    @endif
    <div class="box-header with-border">
        <h3 class="box-title">{{ $isEdit ? __('admin.texts.title_edit_administrator') : __('admin.texts.title_create_administrator') }}</h3>
    </div>
    @include('flash::message')
    <div class="box-body">
        @if($isEdit)
        <input type="hidden" value="{{$admin->id}}" name="id">
        @endif
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'Name:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::text('name', $isEdit ? $admin->name : null, ['class' => 'form-control input-radius name '.($errors->has('name') ? 'is-invalid' : '')]) !!}
                        @if ($errors->has('name'))
                        <span class="text-danger invalid-feedback">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'Last Name:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::text('last_name', $isEdit ? $admin->last_name : null, ['class' => 'form-control input-radius last_name '.($errors->has('last_name') ? 'is-invalid' : '')]) !!}
                        @if ($errors->has('last_name'))
                        <span class="text-danger invalid-feedback">{{ $errors->first('last_name') }}</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'First Name:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::text('first_name', $isEdit ? $admin->first_name : null, ['class' => 'form-control input-radius first_name '.($errors->has('first_name') ? 'is-invalid' : '')]) !!}
                        @if ($errors->has('first_name'))
                        <span class="text-danger invalid-feedback">{{ $errors->first('first_name') }}</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'English Last Name:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::text('last_name_e', $isEdit ? $admin->last_name_e : null, ['class' => 'form-control input-radius last_name_e '.($errors->has('last_name_e') ? 'is-invalid' : '')]) !!}
                        @if ($errors->has('last_name_e'))
                        <span class="text-danger invalid-feedback">{{ $errors->first('last_name_e') }}</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'English First Name:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::text('first_name_e', $isEdit ? $admin->first_name_e : null, ['class' => 'form-control input-radius first_name_e '.($errors->has('last_name_e') ? 'is-invalid' : '')]) !!}
                        @if ($errors->has('first_name_e'))
                        <span class="text-danger invalid-feedback">{{ $errors->first('first_name_e') }}</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'Photo:', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        <input type="file" class="form-control input-radius avatar" name="avatar">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'Email Address:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::text('email', $isEdit ? $admin->email : null, ['class' => 'form-control input-radius email '.($errors->has('email') ? 'is-invalid' : '')]) !!}
                        @if ($errors->has('email'))
                        <span class="text-danger invalid-feedback">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'Password:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::password('password', ['class' => 'form-control input-radius password '.($errors->has('password') ? 'is-invalid' : '')]) !!}
                        @if ($errors->has('password'))
                        <span class="text-danger invalid-feedback">{{ $errors->first('password') }}</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'Password Confirm:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::password('password_confirmation', ['class' => 'form-control input-radius password_confirmation']) !!}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'Gender:', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        <div class="radio">
                            <label class="">
                                <input type="radio" name="gender" class="minimal gender" value="0" {{ ($isEdit && !$admin->gender) ? 'checked' : '' }}>Male
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" name="gender" class="minimal gender" value="1" {{ ($isEdit && $admin->gender) ? 'checked' : '' }}>Female
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group date">
                    {!! Form::label('title', 'Birthday:<span class="text-red">*</span>', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-4">
                        {!! Form::text('birthday', $isEdit ? ($admin->birthday ? date('Y/m/d', strtotime($admin->birthday)) : '') : null, ['class' => 'form-control input-radius datepicker birthday '.($errors->has('birthday') ? 'is-invalid' : ''), 'placeholder' => 'mm/dd/yyyy']) !!}
                        @if ($errors->has('birthday'))
                        <span class="text-danger invalid-feedback">{{ $errors->first('birthday') }}</span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::label('title', 'Address:', ['class'=> 'col-sm-3 control-label'], false) !!}
                    <div class="col-sm-6">
                        {!! Form::text('address', $isEdit ? $admin->address : null, ['class' => 'form-control input-radius address']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer text-center">
        <button type="submit" class="btn btn-primary">@lang('admin.common.save')</button>
    </div>
    <!-- /.box-footer -->
{!! Form::close () !!}

src/adminlte/resources/views/admin/administrator/index.blade.php
@extends('layouts.admin')
@section('title', 'Administrator List')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1 class="breadcrumb-title">
            Administrator
            <small>List</small>
        </h1>
        <div class="pull-right">
            <a href="{{ route('administrators.create') }}" class="btn bg-green btn-flat"><i class="fa fa-plus"></i> New</a>
        </div>
    </section>
    <section class="content">
        @include('flash::message')
        <div class="row box-search">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Filter Administrator List</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    {!! Form::open(['method' => 'GET', 'url' => route("administrators.index"), 'class' => 'form-horizontal']) !!}
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        {!! Form::label('title', 'Name', ['class'=> 'col-sm-4 control-label']) !!}
                                        <div class="col-sm-8">
                                            {!! Form::text('name', request('name'), ['class' => 'form-control input-radius name']) !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        {!! Form::label('title', 'Email', ['class'=> 'col-sm-4 control-label']) !!}
                                        <div class="col-sm-8">
                                            {!! Form::text('email', request('email'), ['class' => 'form-control input-radius email']) !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer text-center">
                            <button type="submit" class="btn btn-primary">{{ __('admin.common.search') }}</button>
                        </div>
                    <!-- /.box-footer -->
                    {!! Form::close () !!}
                </div>
            </div>
        </div>
        <div class="row box-result">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Listing</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Birthday</th>
                                    <th>Role</th>
                                    <th class="action">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($administrators as $val)
                                <tr>
                                    <td>{{ $val->id }}</td>
                                    <td>{{ $val->name }}</td>
                                    <td>{{ $val->email }}</td>
                                    <td class="text-center">{{ $val->birthday ? date('Y/m/d', strtotime($val->birthday)) : '' }}</td>
                                    <td>{!! $val->roles->pluck('name')[0] !!}</td>
                                    <td class="text-center">
                                        <!-- <button type="button" class="btn btn-primary btn-sm">Login</button> -->
                                        <a href="{{ route('administrators.show', $val->id) }}" class="btn btn-primary btn-sm">Show</a>
                                        <a href="{{ route('administrators.edit', $val->id) }}" class="btn btn-info btn-sm">Edit</a>
                                        {!! Form::open(['url' => route('administrators.destroy', $val->id),'method' => 'DELETE', 'class' => 'form-delete']) !!}
                                        <button type="button" class="btn btn-danger btn-sm btn-delete" data-id="{{ $val->id }}" data-table="administrators">Delete</button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix float-right">
                        {!! $administrators->appends(request()->query())->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection